### ISSUE TITLE
Swing mode change doesn't work. 

### ISSUE THREAD

**Issue by harrywenjie** [bigmoby/fglair_for_homeassistant#1]
As stated in title, everything else works great. Thanks.

**Comment by harrywenjie** [comment]
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/fglair_heatpump_controller/climate.py:210
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:48:53 (2 occurrences)
Last logged: 13:18:19

[1634486328] 'NoneType' object is not subscriptable
[1688848368] 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 478, in async_set_swing_mode
    await self.hass.async_add_executor_job(self.set_swing_mode, swing_mode)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 210, in set_swing_mode
    self._fujitsu_device.changeSwingMode(swing_mode)
  File "/usr/local/lib/python3.9/site-packages/pyfujitseu/splitAC.py", line 122, in changeSwingMode
    self.af_vertical_direction = 0
  File "/usr/local/lib/python3.9/site-packages/pyfujitseu/splitAC.py", line 335, in af_vertical_direction
    self._api._set_device_property(self.af_vertical_direction['key'],properties)
TypeError: 'NoneType' object is not subscriptable

```

**Comment by bigmoby** [comment]
Hi @harrywenjie thanks 👍 I'll try in the next days to tackle it 🐛

**Comment by JulienADD** [comment]
Same issue

**Comment by bigmoby** [comment]
I'm so sorry but, at moment, I've no much time to fix it. Please if you could create a PR, you're welcome! 🙌

**Comment by JulienADD** [comment]
> I'm so sorry but, at moment, I've no much time to fix it. Please if you could create a PR, you're welcome! 🙌

Normally, it's okay, i send the pull request (y)

**Comment by bigmoby** [comment]
Thanks @JulienADD for you PR 👍

https://github.com/bigmoby/fglair_for_homeassistant/pull/4/commits/003ac98f2920ecd4063d5e67f52adf07c747861d
