### ISSUE TITLE
Home assistant reports an issue with FGLair

### ISSUE THREAD

**Issue by willefg** [bigmoby/fglair_for_homeassistant#106]
## System Information

version | core-2024.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4958
Installed Version | 1.34.0
Stage | running
Available Repositories | 1458
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 113.9 GB
disk_used | 8.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.0), Terminal & SSH (9.9.0), File editor (5.8.0), ESPHome (2023.12.9), Grafana (9.1.3), InfluxDB (5.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 4 februari 2024 om 03:12
-- | --
current_recorder_run | 13 februari 2024 om 01:22
estimated_db_size | 232.43 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bigmoby/fglair_for_homeassistant/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

My Home Assistant log showed the following (see Debug logs) and states to report it here. 

### Reproduction steps

1. See log
2.
3.

### Debug logs

```text
2024-02-13 00:41:28.910 WARNING (MainThread) [homeassistant.components.climate.const] SUPPORT_FAN_MODE was used from fglair_heatpump_controller, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please create a bug report at https://github.com/bigmoby/fglair_for_homeassistant/issues
2024-02-13 00:41:28.925 WARNING (MainThread) [homeassistant.components.climate.const] SUPPORT_PRESET_MODE was used from fglair_heatpump_controller, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/bigmoby/fglair_for_homeassistant/issues
2024-02-13 00:41:28.947 WARNING (MainThread) [homeassistant.components.climate.const] SUPPORT_SWING_MODE was used from fglair_heatpump_controller, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please create a bug report at https://github.com/bigmoby/fglair_for_homeassistant/issues
2024-02-13 00:41:28.961 WARNING (MainThread) [homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE was used from fglair_heatpump_controller, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/bigmoby/fglair_for_homeassistant/issues
2024-02-13 00:41:29.559 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.fglair_heatpump_controller.climate.FujitsuClimate'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|FAN_MODE|PRESET_MODE|SWING_MODE: 57>, please create a bug report at https://github.com/bigmoby/fglair_for_homeassistant/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-02-13 00:41:29.560 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.fglair_heatpump_controller.climate.FujitsuClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/bigmoby/fglair_for_homeassistant/issues
2024-02-13 00:41:29.560 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.fglair_heatpump_controller.climate.FujitsuClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/bigmoby/fglair_for_homeassistant/issues
2024-02-13 00:41:29.561 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.fglair_heatpump_controller.climate.FujitsuClimate'>) implements HVACMode(s): off, heat, cool, auto, dry, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/bigmoby/fglair_for_homeassistant/issues
```

**Comment by SrBurner** [comment]
Same here!
Seems that home Assistant have decided to change the name of some variables and the plugins needs to adapt it also in order to comply, if I’m correct.

**Comment by charstring1** [comment]
Same here. 

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:599
Integration: Climate (documentation, issues)
First occurred: February 23, 2024 at 7:19:55 AM (2 occurrences)
Last logged: 8:34:43 AM

fglair_heatpump_controller: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1259, in async_device_update
    await self.async_update()
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 377, in async_update
    await self._fujitsu_device.async_get_display_temperature_degree()
  File "/usr/local/lib/python3.12/site-packages/pyfujitsugeneral/splitac.py", line 294, in async_get_display_temperature_degree
    display_temperature_value = self._display_temperature["value"]
                                ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'value'

```

**Comment by AlbertoV8** [comment]
I think I have the same problem. I have it since I update HA for 2024.03, it's stop working and no entity is created when I reinstall it. My log:
@**fglair_heatpump_controller: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 682, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1262, in async_device_update
    await self.async_update()
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 383, in async_update
    self._fan_mode = self.fan_mode
                     ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 322, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 427, in fan_mode
    DICT_FAN_MODE[self._fujitsu_device.get_fan_speed_desc()],
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyfujitsugeneral/splitac.py", line 161, in get_fan_speed_desc
    return FAN_SPEED_DICT[self.get_fan_speed()["value"]]
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 5**

Please, Any help would be appreciatted. I am new in HA and I tried to downgrade to version 0.27 like othes issues request said but I don't know how to downgrade to a older than 0.30 version. Thanks.

**Comment by SgtFlippy** [comment]
I noticed some issues as well. My old cards stopped working, but I can replace them with climate.room instead of climate.name

**Comment by Korvenwin** [comment]
I’m having same issue since last Home Assistant update.

**Comment by bigmoby** [comment]
This issue has been solved with v0.3.5

**Comment by Korvenwin** [comment]
Thank you very much!!!

**Comment by bigmoby** [comment]
@Korvenwin thank you for your "beer" contribution, I appreciate it a lot! 🙏 Many thanks!

**Comment by Korvenwin** [comment]
> @Korvenwin thank you for your "beer" contribution, I appreciate it a lot! 🙏 Many thanks!

The problem occurs again. Please, take a look at issuel #107

**Comment by bigmoby** [comment]
This issue has been solved as the first bug description. The others requests will be already highlighted at https://github.com/bigmoby/fglair_for_homeassistant/issues/107
