### ISSUE TITLE
AP-WF1E HVAC not loaded anymore in integration when logging to FGLair.

### ISSUE THREAD

**Issue by OlivierBlain** [bigmoby/fglair_for_homeassistant#210]
### System Health details

I have two Fujitsu HVACs, one that prefix AC-UTY and another that prefix AP-WF1E. Both were working perfectly under FGLair HACS Custom Integration since I have integrated them with Home Assistant. However, I have just noticed that the AP-WF1E device was not taking any changes made to the controls. I tried to delete the integration load it back but its now only loading my AC-UTY unit; not the AP-WF1E unit.

This is what i get in the log detail:

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:728
integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 10:20:55 AM (4 occurrences)
Last logged: 10:47:41 AM

fglair_heatpump_controller: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
await self.async_update()
File "/config/custom_components/fglair_heatpump_controller/climate.py", line 426, in async_update
self._fan_mode = self.fan_mode
^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/climate/init.py", line 324, in getattribute
return super().getattribute(__name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/fglair_heatpump_controller/climate.py", line 466, in fan_mode
DICT_FAN_MODE[self._fujitsu_device.get_fan_speed_desc()],
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pyfujitsugeneral/splitAC.py", line 213, in get_fan_speed_desc
return FAN_SPEED_DICT[fan_speed]
~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 6

Does anybody have this issue?

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bigmoby/fglair_for_homeassistant/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have two Fujitsu HVACs, one that prefix AC-UTY and another that prefix AP-WF1E. Both were working perfectly under FGLair HACS Custom Integration since I have integrated them with Home Assistant. However, I have just noticed that the AP-WF1E device was not taking any changes made to the controls. I tried to delete the integration load it back but its now only loading my AC-UTY unit; not the AP-WF1E unit.



### Reproduction steps

1.In Device/Integration, in FGLair heat pump controller integration, delete entries
2.Enable integration debugging
3.Add Entry; Email, Passwd, Region (US) of your FGLair account and keep default for other parameter then submit
4.Success; Created configuration; Finish
5.It has only created one entity for my AC-UTY HVAC; No Entry was crated for my AP-WF1E HVAC
6.Pull the log from Home assistant Core for FGLair.


### Debug logs

```text
Logger: homeassistant.components.fujitsu_fglair.coordinator
Source: helpers/update_coordinator.py:382
integration: FGLair (documentation, issues)
First occurred: November 27, 2024 at 10:41:33 AM (10 occurrences)
Last logged: November 27, 2024 at 3:53:18 PM

Unexpected error fetching Fujitsu HVAC data data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fujitsu_fglair/coordinator.py", line 46, in _async_update_data
    devices = await self.api.async_get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ayla_iot_unofficial/ayla_iot_unofficial.py", line 289, in async_get_devices
    devices.append(FujitsuHVAC(self, d, europe=self.europe))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ayla_iot_unofficial/fujitsu_hvac.py", line 98, in __init__
    raise DeviceNotSupportedError("This device is not supported by FujitsuHVAC.")
ayla_iot_unofficial.fujitsu_hvac.DeviceNotSupportedError: This device is not supported by FujitsuHVAC.


Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:728
integration: Climate (documentation, issues)
First occurred: November 27, 2024 at 10:20:55 AM (5 occurrences)
Last logged: November 27, 2024 at 4:01:59 PM

fglair_heatpump_controller: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 426, in async_update
    self._fan_mode = self.fan_mode
                     ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 466, in fan_mode
    DICT_FAN_MODE[self._fujitsu_device.get_fan_speed_desc()],
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyfujitsugeneral/splitAC.py", line 213, in get_fan_speed_desc
    return FAN_SPEED_DICT[fan_speed]
           ~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 6
```


### Diagnostics dump

_No response_

**Comment by bigmoby** [comment]
Hi @OlivierBlain, unfortunately, I can’t quite understand whether it’s truly an issue related to the integration or not. Could you please let me know if the problem persists when downgrading the library?

**Comment by thestu90** [comment]
Mine too has stopped working since the upgrade. Downgraded and now it still won't work :( 

Also doesn't work with the official integration something about doesn't accept HVAC.

Hase been working flawlessly for years since last update though!

**Comment by bigmoby** [comment]
Hi guy, If it had been an issue caused by an integration bug, a downgrade would have fixed the problem. Don’t you think? Have you tried installing two or three versions back? And with each new installation, did you restart Home Assistant?!

**Comment by tOsaer** [comment]
I have the same, it started after I had to updates on Home Assistant itself, the core and the os?

**Comment by bigmoby** [comment]
> updates on Home Assistant itself

oook, so not the custom integration?!

**Comment by c625v12** [comment]
I actually just updated home assistant to the december update 12.0 and operating system to 14. I did not see the error come up after updating to the december update. I saw it come after updating the operating system to 14

**Comment by c625v12** [comment]
I downgraded home assistant to version 2024.11.3 and everything works fine again

**Comment by axelsegers** [comment]
Same here. not working anymore

**Comment by bigmoby** [comment]
Guys, I apologize but in this issue that @OlivierBlain opened, things have become completely unclear! The logs posted are apparently two completely unrelated ones: the first one refers to the integration that has been in the Home Assistant core for some months now:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fujitsu_fglair/coordinator.py", line 46, in _async_update_data
    devices = await self.api.async_get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ayla_iot_unofficial/ayla_iot_unofficial.py", line 289, in async_get_devices
    devices.append(FujitsuHVAC(self, d, europe=self.europe))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ayla_iot_unofficial/fujitsu_hvac.py", line 98, in __init__
    raise DeviceNotSupportedError("This device is not supported by FujitsuHVAC.")
ayla_iot_unofficial.fujitsu_hvac.DeviceNotSupportedError: This device is not supported by FujitsuHVAC.
```  

I consider this unrelated to the support for my custom integration. The second log:  

```
fglair_heatpump_controller: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 426, in async_update
    self._fan_mode = self.fan_mode
                     ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 466, in fan_mode
    DICT_FAN_MODE[self._fujitsu_device.get_fan_speed_desc()],
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyfujitsugeneral/splitAC.py", line 213, in get_fan_speed_desc
    return FAN_SPEED_DICT[fan_speed]
           ~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 6
```  

is of a completely different nature and has nothing to do with the issue title `AP-WF1E HVAC not loaded anymore in integration when logging to FGLair` because this second log shows that the air conditioner has been correctly integrated, but is encountering an exception because it's unable to map the correct value returned by the API (specifically 6). 

Now, there is a suggestion that it might be related to the Home Assistant 2024.12.0 release, which could indeed be the case... I see, from quickly reading the changelog, that this PR was merged: https://github.com/home-assistant/core/pull/125578... it could be... I'm not sure at the moment.  

I kindly ask you to open issues on GitHub in a clear and detailed manner, following the proposed template.

Thank you for your collaboration,
Fabio
