### ISSUE TITLE
Can't see devices after installation

### ISSUE THREAD

**Issue by randommonth** [bigmoby/fglair_for_homeassistant#3]
Hi there, I followed the installation instructions to the best of my ability but cannot see my Fujitsu devices in Home Assistant.

I installed HACS, added the custom repository, installed the FGLAir integration, restarted, updated the configuration.yaml with my login details and restarted. But cannot see my air conditioners in Home Assistant... what else should I have done?

**Comment by bigmoby** [comment]
Hi @randommonth , no climate device in your Developer tools board appears?!

**Comment by randommonth** [comment]
Hi there, no I can't see any Climate device in my Developer Tools board.

All I can see are tabs for YAML, STATES, SERVICES, TEMPLATE, EVENTS,
STATISTICS.

Regards

Tom

**Comment by bigmoby** [comment]
Hi @randommonth , yes sure in States tab, please check it in States tab

**Comment by randommonth** [comment]
Hi, no there's nothing in the States taab referring to Climate, FGLAir or
anything else that could be my air conditioners.

Tom

**Comment by randommonth** [comment]
I have found reference to Climate under the Services tab. But there are no
Climate devices.

[image: image.png]

**Comment by randommonth** [comment]
The logs have the following error:

Logger: homeassistant.components.climate
Source: custom_components/fglair_heatpump_controller/climate.py:81
Integration: Climate (documentation, issues)
First occurred: 9:02:45 PM (1 occurrences)
Last logged: 9:02:45 PM

Error while setting up fglair_heatpump_controller platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",
line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58,
in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fglair_heatpump_controller/climate.py",
line 81, in setup_platform
    if not fglairapi._authenticate():
  File "/usr/local/lib/python3.10/site-packages/pyfujitseu/api.py", line
105, in _authenticate
    response = self._call_api("POST",
  File "/usr/local/lib/python3.10/site-packages/pyfujitseu/api.py", line
164, in _call_api
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line
1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url:
https://user-field-eu.aylanetworks.com/users/sign_in.json

**Comment by chiefcomm** [comment]
Hi @randommonth did you solve this?  From my experience it is related to the region where your account is hosted, as example my account is hosted on the US server (I believe) therefore if I choose eu (or cn) in the config my connection to the server fails with the same error.

2022-12-28 09:12:47.828 ERROR (MainThread) [homeassistant.components.climate] Error while setting up fglair_heatpump_controller platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/fglair_heatpump_controller/climate.py", line 70, in setup_platform
if not fglairapi._authenticate():
File "/usr/local/lib/python3.10/site-packages/pyfujitseu/api.py", line 105, in _authenticate
response = self._call_api("POST",
File "/usr/local/lib/python3.10/site-packages/pyfujitseu/api.py", line 164, in _call_api
response.raise_for_status()
File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://user-field-eu.aylanetworks.com/users/sign_in.json

**Comment by bigmoby** [comment]
@randommonth I'm closing this issue, as @chiefcomm suggested please try another region from your configuration.
