### ISSUE TITLE
Error while setting up fglair_heatpump_controller -- KeyError: 'value'

### ISSUE THREAD

**Issue by jaik3n** [bigmoby/fglair_for_homeassistant#32]
Home Assistant OS 2023.3
Raspberry Pi 4 B

Updated to 0.2.0 and received this error:

```
Logger: homeassistant.components.climate
Source: custom_components/fglair_heatpump_controller/climate.py:190
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 4:25:32 PM (1 occurrences)
Last logged: 4:25:32 PM

Error while setting up fglair_heatpump_controller platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 111, in setup_platform
    add_entities(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _schedule_add_entities
    list(new_entities),
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 112, in <genexpr>
    FujitsuClimate(fglairapi, dsn, region, temperature_offset) for dsn in devices
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 133, in __init__
    self._current_temperature = self.current_temperature
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 190, in current_temperature
    _LOGGER.debug("Display_temperature: %s", curtemp["value"])
KeyError: 'value'
```

**Comment by jaik3n** [comment]
Tried reverting to 2023.2.5
and get the same error:

```
Logger: homeassistant.components.climate
Source: custom_components/fglair_heatpump_controller/climate.py:190
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 4:53:07 PM (1 occurrences)
Last logged: 4:53:07 PM

Error while setting up fglair_heatpump_controller platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 111, in setup_platform
    add_entities(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _schedule_add_entities
    list(new_entities),
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 112, in <genexpr>
    FujitsuClimate(fglairapi, dsn, region, temperature_offset) for dsn in devices
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 133, in __init__
    self._current_temperature = self.current_temperature
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 190, in current_temperature
    _LOGGER.debug("Display_temperature: %s", curtemp["value"])
KeyError: 'value'
```

**Comment by bigmoby** [comment]
Please try to revert to the previous version of fgliar integration (not HA) while I'll try to fix it

**Comment by bigmoby** [comment]
Hi @jaik3n please could you set the fglair logger in debug status and post here the trace?

**Comment by jaik3n** [comment]
> 

Sorry, I'm still pretty new to all of HA stuff and YAML specifically. How do I set the logger to debug status for fglair?

**Comment by bigmoby** [comment]
Yes it was very helpful thanks 👍 I'll fix it.
I don't understand why current temperature is void but...I will fix the code

**Comment by jaik3n** [comment]
also, separate question, but is there a reason to set the temperature at -2 in the config file as you do in the readme? instead of keeping it default at 0?

**Comment by bigmoby** [comment]
> also, separate question(not sure a better place to ask it), but is there a reason to set the temperature at -2 in the config file as you do in the readme? instead of keeping it default at 0?

It's only a sample, in order to be more precise it's my current configuration and I supposed to be a right default. Please check your offset temperature with an external temperature monitor and set in the config the right offset for you.

**Comment by bigmoby** [comment]
Hi @jaik3n please try the new release v0.2.2
