### ISSUE TITLE
Veritcal Swing Keyvalue issue

### ISSUE THREAD

**Issue by jaik3n** [bigmoby/fglair_for_homeassistant#33]
Just updated to 0.2.2

and similar to the current temp issue from 0.2.0 I'm getting this error:

```
2023-03-04 09:31:02.881 INFO (MainThread) [homeassistant.components.climate] Setting up climate.fglair_heatpump_controller
2023-03-04 09:31:02.883 DEBUG (SyncWorker_5) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate setup_platform called
2023-03-04 09:31:02.884 DEBUG (SyncWorker_5) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate config.get
2023-03-04 09:31:06.370 DEBUG (SyncWorker_5) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate init called for dsn: AC000W002554340
2023-03-04 09:31:12.298 DEBUG (SyncWorker_5) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate _fujitsu_device setup.
2023-03-04 09:31:12.298 DEBUG (SyncWorker_5) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate name set: Master Bedroom
2023-03-04 09:31:12.298 DEBUG (SyncWorker_5) [custom_components.fglair_heatpump_controller.climate] Master Bedroom
2023-03-04 09:31:12.299 DEBUG (SyncWorker_5) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate fan_mode: low
2023-03-04 09:31:12.299 DEBUG (SyncWorker_5) [custom_components.fglair_heatpump_controller.climate] Master Bedroom
2023-03-04 09:31:12.299 DEBUG (SyncWorker_5) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate hvac_mode: 6
2023-03-04 09:31:12.301 DEBUG (SyncWorker_5) [custom_components.fglair_heatpump_controller.climate] Master Bedroom
2023-03-04 09:31:12.303 ERROR (MainThread) [homeassistant.components.climate] Error while setting up fglair_heatpump_controller platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/fglair_heatpump_controller/climate.py", line 111, in setup_platform
add_entities(
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _schedule_add_entities
list(new_entities),
File "/config/custom_components/fglair_heatpump_controller/climate.py", line 112, in <genexpr>
FujitsuClimate(fglairapi, dsn, region, temperature_offset) for dsn in devices
File "/config/custom_components/fglair_heatpump_controller/climate.py", line 137, in __init__
self._swing_mode = self.swing_mode
File "/config/custom_components/fglair_heatpump_controller/climate.py", line 300, in swing_mode
self._fujitsu_device.af_vertical_swing["value"],
KeyError: 'value'
```

**Comment by jaik3n** [comment]
If I comment out these parts in climate.py I get no issues.
(starts at line 294)

I'm not sure if it's just snagging an error at vertical_swing and halting, and would encounter another value issue with horizontal_swing, or if it's just the vertical_swing value causing the issue.

I lean towards the former of horizontal_swing also likely causing an issue as well if just vertical_swing is fixed by itself.

```
    @property
    def swing_mode(self) -> str:
        """Return the swing setting."""
#        _LOGGER.debug(self._name)
#        _LOGGER.debug(
#            "FujitsuClimate swing vertical settings: %s",
#           self._fujitsu_device.af_vertical_swing["value"],
#        )
#        _LOGGER.debug(self._name)
#        _LOGGER.debug(
#            "FujitsuClimate swing horizontal settings: %s",
#            self._fujitsu_device.af_horizontal_swing["value"],
#        )

#        if (
#            self._fujitsu_device.af_vertical_swing["value"] == 1
#            and self._fujitsu_device.af_horizontal_swing["value"] == 1
#        ):
#            return "on"
#        elif (
#            self._fujitsu_device.af_vertical_swing["value"] == 1
#            and self._fujitsu_device.af_horizontal_swing["value"] == 0
#        ):
#            return "vertical"
#        elif (
#            self._fujitsu_device.af_vertical_swing["value"] == 0
#            and self._fujitsu_device.af_horizontal_swing["value"] == 1
#        ):
#            return "horizontal"
#        else:
            return "off"

    @property
    def swing_modes(self) -> list[Any]:
        """List of available swing modes."""
        return self._swing_modes

#    def set_swing_mode(self, swing_mode: Any) -> None:
#        """Set new target swing."""
#        _LOGGER.debug(self._name)
#        _LOGGER.debug("FujitsuClimate swing choice: %s", swing_mode.upper())
#        if swing_mode.upper() == "ON":
#            self._fujitsu_device.af_vertical_swing = 1
#            self._fujitsu_device.af_horizontal_swing = 1
#            _LOGGER.debug(self._name)
#            _LOGGER.debug("FujitsuClimate swing choice valide: ON")
#        if swing_mode.upper() == "OFF":
#            self._fujitsu_device.af_vertical_swing = 0
#            self._fujitsu_device.af_horizontal_swing = 0
#            _LOGGER.debug(self._name)
#            _LOGGER.debug("FujitsuClimate swing choice valide: OFF")
#        if swing_mode.upper() == "VERTICAL":
#           self._fujitsu_device.af_vertical_swing = 1
#           self._fujitsu_device.af_horizontal_swing = 0
#           _LOGGER.debug(self._name)
#            _LOGGER.debug("FujitsuClimate swing choice valide: VERTICAL")
#        if swing_mode.upper() == "HORIZONTAL":
#            self._fujitsu_device.af_vertical_swing = 0
#            self._fujitsu_device.af_horizontal_swing = 1
#            _LOGGER.debug(self._name)
#            _LOGGER.debug("FujitsuClimate swing choice valide: HORIZONTAL")
        # if swing_mode.upper() == 'BOTH':
        #    self._fujitsu_device.af_vertical_swing = 1
        #    self._fujitsu_device.af_horizontal_swing = 1
        #    _LOGGER.debug("FujitsuClimate swing choice valide: BOTH")
```

**Comment by jaik3n** [comment]
Additionally, after commenting out that section, although I get no errors in the log, My devices aren't showing up under my devices or entities.

I'm not sure if that's because of this issue or something unrelated. I've tried previous versions of the fglair integration, but all of them have caused errors of some kind, so I haven't been able to see the devices show up in any version so far that I've tried (I believe I've tried 0.1.2, 0.1.8, 0.1.9, 0.2.0, and 0.2.2 at this time)

**Comment by bigmoby** [comment]
Hi @jaik3n really I don't understand why you get this error...a different HVAC model...I don't know. Please could you post here the logger trace after `FujitsuClimate init fine.` ? (in other words the full property list logged)
Thanks, 
Fabio

**Comment by jaik3n** [comment]
here is the full log:

```
2023-03-04 12:30:58.647 INFO (MainThread) [homeassistant.components.climate] Setting up climate.fglair_heatpump_controller
2023-03-04 12:30:58.652 DEBUG (SyncWorker_1) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate setup_platform called
2023-03-04 12:30:58.652 DEBUG (SyncWorker_1) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate config.get 
2023-03-04 12:31:04.654 DEBUG (SyncWorker_1) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate init called for dsn: AC000W002554340
2023-03-04 12:31:08.649 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform fglair_heatpump_controller is taking over 10 seconds.
2023-03-04 12:31:11.377 DEBUG (SyncWorker_1) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate _fujitsu_device setup.
2023-03-04 12:31:11.377 DEBUG (SyncWorker_1) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate name set: Master Bedroom
2023-03-04 12:31:11.378 DEBUG (SyncWorker_1) [custom_components.fglair_heatpump_controller.climate] Master Bedroom
2023-03-04 12:31:11.378 DEBUG (SyncWorker_1) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate fan_mode: low
2023-03-04 12:31:11.378 DEBUG (SyncWorker_1) [custom_components.fglair_heatpump_controller.climate] Master Bedroom
2023-03-04 12:31:11.378 DEBUG (SyncWorker_1) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate hvac_mode: 6
2023-03-04 12:31:11.378 DEBUG (SyncWorker_1) [custom_components.fglair_heatpump_controller.climate] Master Bedroom
2023-03-04 12:31:11.381 ERROR (MainThread) [homeassistant.components.climate] Error while setting up fglair_heatpump_controller platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 111, in setup_platform
    add_entities(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _schedule_add_entities
    list(new_entities),
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 112, in <genexpr>
    FujitsuClimate(fglairapi, dsn, region, temperature_offset) for dsn in devices
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 137, in __init__
    self._swing_mode = self.swing_mode
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 300, in swing_mode
    self._fujitsu_device.af_vertical_swing["value"],
KeyError: 'value'

```

**Comment by jaik3n** [comment]
I believe this is the line you're looking for?
`2023-03-04 12:31:04.654 DEBUG (SyncWorker_1) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate init called for dsn: AC000W002554340`

**Comment by bigmoby** [comment]
> I believe this is the line you're looking for?
> `2023-03-04 12:31:04.654 DEBUG (SyncWorker_1) [custom_components.fglair_heatpump_controller.climate] FujitsuClimate init called for dsn: AC000W002554340`

The line 163, full log (please obfuscate any sensitive data if any).

**Comment by jaik3n** [comment]
Sorry, I'm a little confused about where to find that/ how to get that. I can provide a full debug log of my entire HA? it's big though. Otherwise, with this in the config file:
```
 logger:
  default: critical
  logs:
    custom_components.fglair_heatpump_controller.climate: debug
    homeassistant.components.climate: debug
```

The above is what I get when I go to Settings > System > Logs, and download the full logs, or just Load full logs

**Comment by bigmoby** [comment]
>  Sorry, I'm a little confused about where to find that/ how to get that. I can provide a full debug log of my entire HA? it's big though. Otherwise, with this in the config file:
> ```
>  logger:
>   default: critical
>   logs:
>     custom_components.fglair_heatpump_controller.climate: debug
>     homeassistant.components.climate: debug
> ```
> 
> The above is what I get when I go to Settings > System > Logs, and download the full logs, or just Load full logs

Uh no, no prob I'll try to apply a null point check before. It's a unusual behavior, I don't know if other people are affected by... however I'll try to fix it👍

**Comment by bigmoby** [comment]
There's now an unsolved bug, I'm sorry I'll try to fix asap

**Comment by jaik3n** [comment]
I'm in no rush!!! I just want to be helpful! :) thank you for all your work on this integration!

**Comment by jaik3n** [comment]
also, just an FYI, i know the 0.2.3 created a new unresolved bug, but I have a log here that maybe could help?

https://pastebin.com/3kuBk6EA

It's pretty big, but at the end, it looks like it's pulling a null / void value for self._fujitsu_device.powerful_mode as well now.

Maybe it's just one unit? but I'm not really sure how best to read this log, but maybe there's something in here that would help?

**Comment by bigmoby** [comment]
Hi @jaik3n uh yes this log is what I'm searching for 🙌 thanks!
The current bug relates on unsaved swing status after a swing change.

**Comment by jaik3n** [comment]
Great!
I don't know exactly what changed for me to get this full log, but I did the same actions as before, so I'm glad this is helpful!!!!

**Comment by bigmoby** [comment]
Hi @jaik3n please try this release: https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.2.4
