### ISSUE TITLE
Keyvalue Error / Void return 

### ISSUE THREAD

**Issue by jaik3n** [bigmoby/fglair_for_homeassistant#38]
It's not quite there yet, but I do now see that the entities for the AC units are populating in the Devices/Integrations. Although they seem to disconnect from the integration hitting an error.

It appears to be another void return?

```
Logger: homeassistant.components.climate
Source: custom_components/fglair_heatpump_controller/climate.py:413
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 3:56:06 PM (2 occurrences)
Last logged: 3:56:06 PM

Error adding entities for domain climate with platform fglair_heatpump_controller
Error while setting up fglair_heatpump_controller platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 807, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 602, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 338, in state_attributes
    data[ATTR_PRESET_MODE] = self.preset_mode
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 413, in preset_mode
    self._fujitsu_device.powerful_mode["value"],
KeyError: 'value'
```

Here is the full log:
https://pastebin.com/PPL7J4mj

 (former issue here: https://github.com/bigmoby/fglair_for_homeassistant/issues/33 )

**Comment by bigmoby** [comment]
Hi @jaik3n please try this new release version: https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.2.5
I suppose however that there is something weird in your AC...probably an AC model that not support swing or preset mode...I don't know 🤔
Anyway...enjoy: https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.2.5
