### ISSUE TITLE
Target temperature as 6553,5 when Air Conditioner is off

### ISSUE THREAD

**Issue by jfisbein** [bigmoby/fglair_for_homeassistant#45]
Some minutes after turning the air conditioner off, the target temperature is shown as 6553.5 which is a little bit more than a comfortable one ;-)
![image](https://github.com/bigmoby/fglair_for_homeassistant/assets/272565/679b0314-467d-4304-ac22-1667f1a114e3)

Looks like, the integration has not been able to read it and it's showing this value, maybe some change can be made to show it empty in this scenario.

**Comment by bigmoby** [comment]
Hi @jfisbein , 
oh yes, it is absolutely normal! ...it's summertime, guy! 😅 well...I'm joking of course!
Ok, it is a little bit abnormal because of this guard:

```
if curtemp["value"] == 65535:
  _LOGGER.debug("Display_temperature value not valid.")
  return None
```

So, I'm assuming you've installed the latest integration version, right? So...the placement of the comma (the point, in your scenario) doesn't sound right to me. Please could you have a test for me? Could you please change the locale in your Home Assistance to understand if it "solves"? Thanks

**Comment by jfisbein** [comment]
I tried setting the locale for my user to Spanish, English and English GB. And I always see the 6553.5 value (in different formats)
![image](https://github.com/bigmoby/fglair_for_homeassistant/assets/272565/d298a217-f1f9-46c6-85a3-3e25a8ccb5c1)
![image](https://github.com/bigmoby/fglair_for_homeassistant/assets/272565/32a9d727-fd9a-4e50-b8e8-983516a61026)
![image](https://github.com/bigmoby/fglair_for_homeassistant/assets/272565/8538ffb1-c488-4771-8307-34e15fef3a01)

**Comment by jfisbein** [comment]
If I can do anything more, please tell me. Iw as thinking in adding a log.trace with the `curtemp` object on line 204, before the `if`.
What do you think?

**Comment by bigmoby** [comment]
Please try with [v0.2.8](https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.2.8)

**Comment by jfisbein** [comment]
It does not work, because the problem is with the **target** temperature, and I think that the path is trying to fix the **current** temperature.

**Comment by andyvn22** [comment]
This is also happening when in "Fan only" mode, I believe (though mine is expressed as 11828°F).

**Comment by bigmoby** [comment]
Please @jfisbein @andyvn22 could you confirm that version https://github.com/bigmoby/fglair_for_homeassistant/releases/tag/v0.2.9 fixes ?

**Comment by andyvn22** [comment]
Confirmed! Thank you!

**Comment by jfisbein** [comment]
I'm not at home, I updated it and now the entity is not available.
![Screenshot_2023-09-23-21-00-03-556_io.homeassistant.companion.android.jpg](https://github.com/bigmoby/fglair_for_homeassistant/assets/272565/9fc78927-98a1-4fae-98a5-f69290f8fcdc)

I have limited access to internet, I will try to gather more info but maybe I won't be able until Thursday.

**Comment by bigmoby** [comment]
Uh damn it!😓 Please downgrade to the previous version. If you can please post here your log!

**Comment by jfisbein** [comment]
I downgraded to 0.2.8 and is still failing.

This is the log I have been able to get using the mobile phone.

```
Logger: homeassistant.components.climate
Source: util/async_.py:151
Integration: Climate (documentation, issues)
First occurred: 23:25:26 (2 occurrences)
Last logged: 23:25:27

Error adding entities for domain climate with platform fglair_heatpump_controller
Error while setting up fglair_heatpump_controller platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1002, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 773, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 308, in state_attributes
    self.target_temperature,
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fglair_heatpump_controller/climate.py", line 239, in target_temperature
    data: float = self._fujitsu_device.adjust_temperature_degree
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyfujitsugeneral/splitAC.py", line 287, in adjust_temperature_degree
    datapoints = self._get_device_property_history(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyfujitsugeneral/splitAC.py", line 501, in _get_device_property_history
    propertyHistory = self._api._get_device_property(propertyCode)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyfujitsugeneral/api.py", line 108, in _get_device_property
    access_token = self._authenticate()
                   ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyfujitsugeneral/api.py", line 129, in _authenticate
    response = self._call_api(
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyfujitsugeneral/api.py", line 189, in _call_api
    response = requests.request(
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1297, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 219, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 164, in protected_loop_func
    check_loop(func, strict=strict)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in check_loop
    raise RuntimeError(
RuntimeError: Blocking calls must be done in the executor or a separate thread; Use `await hass.async_add_executor_job()`; at custom_components/fglair_heatpump_controller/climate.py, line 239: data: float = self._fujitsu_device.adjust_temperature_degree

```

Thanks!

**Comment by bigmoby** [comment]
Hi @jfisbein have tried with the v0.3.0 release?

**Comment by jfisbein** [comment]
I just tried and is still failing but in a different way.
The only fglair related log line I see is:
```
2023-10-16 08:21:04.211 ERROR (MainThread) [homeassistant.components.climate] The fglair_heatpump_controller platform for the climate integration does not support platform setup. Please remove it from your config.
```
And I also had a warning about fglair yaml not being needed anymore.
![Settings-–-Home-Assistant](https://github.com/bigmoby/fglair_for_homeassistant/assets/272565/004f5484-081b-4d1a-9d86-8cfdc1eb4bb1)

**Comment by jfisbein** [comment]
Reconfigured using the new way, but I'm still getting an error.
Attached the debug log.
[fglair_3.0.0.txt](https://github.com/bigmoby/fglair_for_homeassistant/files/12914981/fglair_3.0.0.txt)

looks like there's some problem with the API call, and the response is not in JSON.
`Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8`

**Comment by bigmoby** [comment]
👍ok thanks I'll try to understand!
